### ISSUE TITLE
Magento 2.3.1 Incompatibility

### ISSUE THREAD

**Issue by macguydvd** [fooman/printorderpdf-implementation-m2#1]
I receive the following error on all 3 of my installed Fooman extensions with the new Magento 2.3.1 update.

`fooman/printorderpdf-m2 3.1.0 requires magento/framework 100.1.0 - 102.0.0 -> satisfiable by magento/framework[100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12, 101.0.3, 100.1.13, 101.0.4, 101.0.5, 100.1.14, 100.1.15, 101.0.6, 100.1.16, 101.0.7, 102.0.0, 100.1.17, 101.0.8].`

**Comment by fooman** [comment]
This is expected behaviour. We will be working through our testing to confirm compatibility and once it looks all good push out a new release. As there were no pre-releases for 2.3.1 we were only able to start this process today. Stay tuned.

**Comment by macguydvd** [comment]
Is there a file I could modify in the meantime on my testing server to allow installation? That way I could attempt to locate bugs in an effort to help.

**Comment by macguydvd** [comment]
Just as an FYI these are the particular extensions that are giving this error in my situation:
```
fooman/printorderpdf-m2
fooman/googleanalyticsplus-m2
fooman/emailattachments-m2
fooman/sameorderinvoicenumber-m2
```

**Comment by fooman** [comment]
These should all be available now (with Marketplace going through the approval process now).

If you wanted to help verify in the future you could remove the metapackage and install the implementation packages directly (provided there are no breaking changes in the dependent magento modules this should install).

So the process for the PrintOrderPdf extension would be 
```
composer require (for the new Magento version) --no-update
composer remove fooman/printorderpdf-m2 --no-upate
composer require fooman/printorderpdf-implementation-m2 --no-update
composer update
```
