### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by mrtnstolk** [fooman/printorderpdf-implementation-m2#10]
I get the following error when installing on Magento 2.4

Errors during compilation:
	Fooman\PrintOrderPdf\Model\Pdf\Order
		Incompatible argument type: Required type: \Magento\Framework\Locale\ResolverInterface. Actual type: \Magento\Store\Model\App\Emulation; File:
/var/www/html/magento/vendor/fooman/printorderpdf-implementation-m2/Model/Pdf/Order.php

Anyone have any idea what causes this and how to fix it?
It was installed using the composer command as on the website.

composer require fooman/printorderpdf-m2:^3.0

**Comment by fooman** [comment]
Do you mind checking what exact versions got installed. The output of `composer show fooman/*` would be good. The error message would currently indicate that possibly the 2.4.1 compatible version got installed into 2.4.0. Which version of Magento is this currently using?

**Comment by Gkumar12398** [comment]
hii
