### ISSUE TITLE
Exception on place order $0

### ISSUE THREAD

**Issue by vmartins** [fooman/printorderpdf-implementation-m2#15]
When using native module "[Zero Subtotal Checkout](https://docs.magento.com/user-guide/payment/zero-subtotal-checkout.html)" and placing the order with value $0, displays the error:

```
Exception #0 (Magento\Framework\Exception\LocalizedException): We cannot retrieve the payment info model object.
#1 Magento\Payment\Block\Info->getMethod() called at [vendor/fooman/printorderpdf-implementation-m2/src/Plugin/PaymentInfoBlockPlugin.php:57]
#2 Fooman\PrintOrderPdf\Plugin\PaymentInfoBlockPlugin->aroundGetTemplateFile() called at [vendor/magento/framework/Interception/Interceptor.php:135]
```

**Comment by fooman** [comment]
Thanks for the report. I just double checked this with a fresh install using the latest version of Magento and this extension and was not able to replicate this. 

Please re-open if you are able to provide further info that replicates the issue on a fresh Magento instance.

![image](https://user-images.githubusercontent.com/455508/179876671-21c3c102-7b5e-4f8d-8fc1-c3fa19fb3dbc.png)
