### ISSUE TITLE
delivery information part missing in print order pdf

### ISSUE THREAD

**Issue by rakeshdonga** [fooman/printorderpdf-implementation-m2#6]
Hello
i want to order print pdf in delivery information part add how can do this ? 
in invoice,shipment showing this part but not your order print pdf
https://prnt.sc/pn83v0

**Comment by fooman** [comment]
Deliver Information is not a default Magento feature. It currently looks like another customisation that added this to your site and default pdfs. This would then need to be also applied to the print order pdfs here https://github.com/fooman/printorderpdf-implementation-m2/blob/develop/src/Model/Pdf/Order.php 

best of luck
