### ISSUE TITLE
Getting Error while click Print Button on admin order page

### ISSUE THREAD

**Issue by balwant20** [fooman/printorderpdf-implementation-m2#8]
Hi There,
I have configured your's **PrintOrderPdf**.  but it is not working for me. I am getting an error while I using Print Button to print Order Pdf which I mentioned in below ss. Please check and help me out with this issue. I am using **Magento 2.3.5-p1**.

> app/code/Fooman/PrintOrderPdf/Controller/Adminhtml/Order/PrintAction.php

[public function execute()
    {
        $orderId = $this->getRequest()->getParam('order_id');
        if ($orderId) {
            $order = $this->orderRepository->get($orderId);
            if ($order->getEntityId()) {
                $pdf = $this->orderPdfFactory->create()->getPdf([$order]); // This line is creating Problem
                $date = $this->date->date('Y-m-d_H-i-s');
                $fileContent = ['type' => 'string', 'value' => $pdf->render(), 'rm' => true];
                return $this->fileFactory->create(
                    __('order') . '_' . $date . '.pdf',
                    $fileContent,
                    DirectoryList::VAR_DIR,
                    'application/pdf'
                );
            }
        }
        return $this->resultRedirectFactory->create()->setPath('sales/*/view');
    }](url)

![image](https://user-images.githubusercontent.com/31465231/95574957-7fed1180-0a4b-11eb-9fac-4f31e12230f5.png)

**Comment by fooman** [comment]
It looks like you have manually installed into app/code. Please follow our installation steps as that will provide you with the compatible version for 2.3.5-p1.
