### ISSUE TITLE
Incompatible argument type

### ISSUE THREAD

**Issue by Neusbeer** [fooman/printorderpdf-implementation-m2#9]
got installation error on Magento 2.4 CE / php 7.4
Errors during compilation:
        Fooman\PrintOrderPdf\Model\Pdf\Order
                Incompatible argument type: Required type: \Magento\Framework\Locale\ResolverInterface. Actual type: \Magento\Store\Model\App\Emulation; File:
/home/redacted/domains/redacted/public_html/app/code/Fooman/PrintOrderPdf/Model/Pdf/Order.php

when trying to print an order, I get
"Type Error occurred when creating object: Fooman\PrintOrderPdf\Model\Pdf\Order"

**Comment by fooman** [comment]
@Neusbeer thanks for the report. It looks like you manually installed the extension into app/code. As the latest release is only compatible with 2.4.1 you will get to see this error. Using the recommend Composer installation method you would get the previous release on 2.4.0. - please see installation options [here](https://magento2-support.fooman.co.nz/article/1295-installing-print-order-pdf-m2-from-fooman-website).
